### PR TITLE
Umar-commit: Huge Changes to exiting old software forked from another…

### PR DESCRIPTION
**Pull request by Umar-dev23**
… profile. But The New Features added are..

1. Three Issues of not picking the Address, Phone number, and Website URL now it is able to do that
2. Now we have integrated this with WebInterface. Now you can give input on a Web interface, no need to input on Cmd.
3. Google Maps Api added to the software to get the recommendations for the place as We Search on Google Maps it gives suggestions about the Places it is doing that.

### CODE REVIEW

**Comment by Madi-S** [comment]
Hey,

Are these changes still available on GitHub? You can reopen MR, I will have
a look at it this weekend or next week.
Thanks for your contribution, glad to know that someone is trying to
improve the project

пт, 16 авг. 2024 г., 22:18 Umar-dev23 ***@***.***>:

**Comment by Umar-dev23** [comment]
Hey! 
Thankyou for your appreciation.Yes It is available on GitHub, I am still working on this project to make it more efficient and easy to work. 
This is my old commit which I had made around 4 days ago.. 
You can Visit https://github.com/Umar-dev23/Lead-Generation/tree/master     master branch for most latest changes that I have made to this Project. 
Thank you for Your Consideration

**Comment by Madi-S** [comment]
Once you done, you can push it directly to the origin, I mean open a PR.
Later I can add you as a collaborator so you will be able to push it
directly to the origin without me

сб, 17 авг. 2024 г., 09:45 Umar-dev23 ***@***.***>:

**Comment by Umar-dev23** [comment]
Okay

**Comment by Madi-S** [comment]
@Umar-dev23 @UmarAethon Looks good, I did not test it yet. Have you tested it? Gotta adjust some of the code tho. I will merge it on Monday or Tuesday.

**Comment by Umar-dev23** [comment]
Hey their, 
Glad to hear back from you. But give little bit more time, once I will be done I will open my final pull request. I am still working on it, I have added google maps Api integrated with it, I have added a feature of Google maps search area controlling by this now the city in which we will search it will remain in it by using lat l, lang. Now I am waiting on data it extracted to be shown back on web interface in a tabular form. I am closing this pull request I will make my final pull request back.

**Comment by Madi-S** [comment]
Ok, no worries. I will be waiting for your PR then, good luck

**Pull request closed without merging**
